kind: pipeline
name: build

steps:
  - name: build
    image: nexus.admin.sharecare.com/mhart/alpine-node
    environment:
      NPM_CONFIG_USERCONFIG: /secrets/.npmrc
    commands:
      - npm ci

trigger:
  branch: [ develop, master ]

---
kind: pipeline
name: publish

steps:
  - name: build
    image: nexus.admin.sharecare.com/mhart/alpine-node
    environment:
      NPM_CONFIG_USERCONFIG: /secrets/.npmrc
    commands:
      - npm ci

  - name: publish
    image: nexus.admin.sharecare.com/mhart/alpine-node
    environment:
      NPM_CONFIG_USERCONFIG: /secrets/.npmrc
    commands:
      - npm publish

  - name: teams
    image: nexus.admin.sharecare.com/drone-teams-notification
    settings:
      webhook: 'https://outlook.office.com/webhook/87b7de90-c5c8-4dc9-9235-c1fe3bd41350@4791286b-0707-4782-8dae-89fe4a320b09/IncomingWebhook/8bfd7b92b7c243b5be907232502cd5f5/73208d33-54b5-4aa8-af10-139d155a7ef2'
    when:
      status: [ success, failure ]
      local: false

  - name: email
    image: nexus.admin.sharecare.com/drone-email-notification
    settings:
      addresses: [ 'bbaker@sharecare.com' ]
    when:
      status: [ success, failure ]
      local: false

trigger:
  event: [ tag ]
